apiVersion: v1
kind: Secret
metadata:
  name: {{ template "jenkins.fullname" . }}
  labels:
    app: {{ template "jenkins.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  jenkins-admin-password: {{ default (randAlphaNum 10) .Values.master.adminPassword | b64enc | quote }}
  jenkins-admin-user: {{ default "admin" .Values.master.adminUser | b64enc | quote }}