apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "hookname" . }}
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
  annotations:
    "helm.sh/hook": pre-delete
spec:
  completions: 1
  parallelism: 1
  template:
    metadata:
      name: {{ template "hookname" . }}
      labels:
        heritage: {{.Release.Service | quote }}
        release: {{.Release.Name | quote }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    spec:
     restartPolicy: "Never"
     containers:
      - name: {{ template "hookname" . }}
        image: google/cloud-sdk 
        command: 
          - "/bin/bash"
          - "-cx"
          - |
            # delete pre install hook secrets
            kubectl delete secret jenkins-ssh-{{.Release.Name}} || true;
            kubectl delete secret jenkins-helm-{{.Release.Name}} || true;
            kubectl delete secret jenkins-gke-{{.Release.Name}} || true;