apiVersion: v1
kind: Secret
metadata:
  name: {{ template "jenkins.fullname" . }}-setup
type: Opaque
data:
  {{- $files := .Files }}
  {{ range $path, $bytes := .Files.Glob "groovy/*" }}
  {{ base $path }}: {{ b64enc (tpl ($files.Get $path) $) }}
  {{ end }}