apiVersion: v1
kind: Service
metadata:
  name: {{ template "jenkins.fullname" . }}
  labels:
    app: {{ template "jenkins.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
{{ toYaml .Values.master.service.annotations | indent 4 }}
spec:
  ports:
    - port: {{.Values.master.service.externalPort}}
      name: externalport
      protocol: TCP
      targetPort: {{.Values.master.port}}
    - port: {{.Values.service.port}}
      name: masterport
      protocol: TCP
      targetPort: {{.Values.master.port}}
    - port: {{.Values.agent.port}}
      name: agentport
      protocol: TCP
      targetPort: {{.Values.agent.port}}
  selector:
    component: "{{.Release.Name}}-{{.Values.master.name}}"
  type: {{.Values.master.service.type}}