# Default values for jenkins.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

images:
  jenkinsmaster: "gcr.io/sds-readiness/jenkinsmaster:prod"
  jenkinsagent: "gcr.io/sds-readiness/jenkinsagent:prod"
  jenkinsgradle: "gcr.io/sds-readiness/jenkinsgradle:prod"
  jenkinsshelldev: "gcr.io/sds-readiness/jenkinsshelldev:prod"

adminEmail: "me@email.com"
javaOptions: "-Xms1024m -Xmx1024m -Djenkins.install.runSetupWizard=false"
jenkinsHookUrl:
jenkinsUrl: "jenkins.somedomain.io"
jobsRepo: "URL to jobs repo"
seedJobToken: "seed"

# github, jenkins or ldap
security: "jenkins"
permissiveScriptSecurity: false

metrics:
  accessKey: "changeme"

slack:
  slackDomain: "samsung-cnct"
  slackRoom: "#ping-jenkins"
  slackApiToken: "change me"

github:
  apiUrl: "https://api.github.com"
  manageHooks: true
  clientCacheSize: 20
  clientId: "change me"
  clientKey: "change me"
  admins: "change me"
  botUser: "change me"
  orgNames: "change me"

vault:
  server: "https://vault.prod.svc.cluster.local"
  token: "change me"
  github:
    path: "secret/jenkins-github"
    botAccessToken: "jenkins-bot-access-token"
    
persistence:
  claimName: "dr-jenkins-jobs"
  reclaiming: "Retain"
  enabled: true
  accessMode: "ReadWriteOnce"
  size: 200Gi

agent:
  cpu: "200m"
  memory: "1024Mi"
  port: 50000
  requestsPerHost: 1000

master:
  cpu: "200m"
  memory: "1024Mi"
  port: 8080
  serviceType: "NodePort"

helm:
  serviceAccount: "change me"
